added got functin to manage git worktree checkouts

diff --git a/bashpd b/bashpd
--- a/bashpd
+++ b/bashpd
@@ -1,4 +1,5 @@
 ################################################
+#
 ##          __              .___     .__      ##
 ##    _____/  |______     __| _/____ |  |     ##
 ##  _/ ___\   __\__  \   / __ |/ __ \|  |     ##
@@ -254,21 +255,93 @@ fi
 
 alias notify="notify-send 'Process Completed' 'Please have a look in the terminal' -u 'normal' && /home/prajwal/.local/bin/alert"
 
+function got() {
+    # Handle flags
+    local new_branch=false
+    local migration=false
+    local branch_name=""
+    while [ $# -gt 0 ]; do
+      case $1 in
+        --new|-n)
+          new_branch=true
+          ;;
+        *)
+          branch_name="$1"
+          ;;
+      esac
+      shift
+    done
+
+    # Check if current directory is inside a Git repository
+    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+        echo "Error: Not a Git repository" >&2
+        return 1
+    fi
+
+    repo_path=$(git worktree list | awk 'NR==1{print $1}')
+
+    # Check if branch name argument is provided
+    if [[ -n "$branch_name" ]]; then
+        # Get list of worktrees
+        local worktree_list=$(git worktree list)
+
+        # Loop through worktrees to find branch
+        local branch_dir=""
+        while read -r line; do
+            local dir=$(echo "$line" | awk '{print $1}')
+            local commit=$(echo "$line" | awk '{print $2}')
+            local branch=$(echo "$line" | awk '{print $3}')
+            if [[ "$branch" == "[$branch_name]" ]]; then
+                branch_dir="$dir"
+                break
+            fi
+        done <<< "$worktree_list"
+
+        # Check if branch directory is found
+        if [[ -z "$branch_dir" ]]; then
+            if [[ "$new_branch" == true ]]; then
+                # Create new worktree
+                git worktree add "$repo_path/$branch_name" "$branch_name"
+                branch_dir=$(git worktree list | awk "/\[$branch_name\]/{print \$1}")
+            else
+                echo "Error: Branch directory not found for branch $branch_name" >&2
+                return 1
+            fi
+        fi
+
+        # Change to branch directory
+        cd "$branch_dir"
+
+    else
+        # No branch name argument provided, list worktrees
+        git worktree list
+    fi
+}
+# Autocomplete branch names
+_got_branch_names() {
+  local branches="$(git worktree list | awk 'NR > 1 {gsub(/[][]/, "", $3); print $3}')"
+  COMPREPLY=($(compgen -W "$branches" -- "${COMP_WORDS[COMP_CWORD]}"))
+}
+complete -F _got_branch_names got
+
 ################# ZSHRC ###############
 
-# Plugins currently using
-#plugins=(git zsh-syntax-highlighting zsh-autosuggestions docker)
+# Check if the current shell is zsh
+if [[ $(ps -p $$ | awk '{print $4}' | tail -n 1) == "zsh" ]]; then
+  # Plugins currently using
+  #plugins=(git zsh-syntax-highlighting zsh-autosuggestions docker)
 
-bindkey '^ ' autosuggest-accept
+  bindkey '^ ' autosuggest-accept
 
-# Edit line in vim with ctrl-backspace:
-autoload edit-command-line; zle -N edit-command-line
-bindkey '' edit-command-line
+  # Edit line in vim with ctrl-backspace:
+  autoload edit-command-line; zle -N edit-command-line
+  bindkey '' edit-command-line
 
-bindkey '' backward-kill-word
-bindkey '<C-Del>' kill-word
+  bindkey '' backward-kill-word
+  bindkey '<C-Del>' kill-word
 
-bindkey "" backward-word
+  bindkey "" backward-word
 
-export EDITOR="lvim"
-export VISUAL="lvim"
+  export EDITOR="lvim"
+  export VISUAL="lvim"
+fi
